# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import openunderstand.utils.utilities as module_0


def test_case_0():
    module_0.timer_decorator()
