name: OpenUnderstand CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest
          pip install pytest-cov
          pip install coverage
          pip install setuptools
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest test_utilities.py

      - name: Run coverage analysis
        run: |
          python -m pytest --cov=openunderstand.utils.utilities test_utilities.py